server:
  port: ${USER_SERVICE_PORT:8081}

spring:
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5433/payguard_user}
    username: ${USER_DB_USER:postgres}
    password: ${USER_DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

payguard:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:payguard-user}
    ttl-seconds: ${JWT_TTL_SECONDS:3600}
